services:
  - type: web
    name: busu-karte-v3
    runtime: python
    plan: free
    buildCommand: "python --version"
    startCommand: "python app.py"
    autoDeploy: true
    healthCheckPath: /health
